/* GoBrot – Brotdaten
   Felder: name, alias (optional), land, region, kat, getreide, trieb, text, fakt (optional) */
(() => {
  const REGIONS = ["Europa", "Naher Osten", "Asien", "Afrika", "Amerika", "Ozeanien"];

  const CATEGORIES = [
    { key: "roggen",   label: "Sauerteig & Roggen",   color: "#6b4430" },
    { key: "weizen",   label: "Weizen & Dinkel",      color: "#94680c" },
    { key: "vollkorn", label: "Vollkorn & Körner",    color: "#6f7a2c" },
    { key: "fladen",   label: "Fladenbrot",           color: "#b4532a" },
    { key: "klein",    label: "Kleingebäck",          color: "#2d6a8a" },
    { key: "suess",    label: "Süß & festlich",       color: "#a8386a" },
    { key: "dampf",    label: "Gedämpft & frittiert", color: "#3f7d71" },
    { key: "spezial",  label: "Mais, Maniok & Co.",   color: "#7a5aa6" }
  ];

  const EU = "Europa", NO = "Naher Osten", AS = "Asien", AF = "Afrika", AM = "Amerika", OZ = "Ozeanien";

  const BREADS = [
    // ---------- Deutschland ----------
    { name: "Bauernbrot", land: "Deutschland", region: EU, kat: "roggen", getreide: "Roggen & Weizen", trieb: "Sauerteig",
      text: "Rustikales Mischbrot mit kräftiger, oft bemehlter Kruste und saftiger Krume. Traditionell im Holzofen gebacken und lange frisch.",
      fakt: "Eine feste Rezeptur gibt es nicht – fast jede Region hat ihr eigenes Bauernbrot." },
    { name: "Pumpernickel", land: "Deutschland (Westfalen)", region: EU, kat: "vollkorn", getreide: "Roggenschrot", trieb: "Sauerteig",
      text: "Dunkles, dichtes Brot aus Roggenschrot, das 16 bis 24 Stunden bei niedriger Temperatur im Dampf gebacken wird. Schmeckt mild und leicht süßlich.",
      fakt: "Die dunkle Farbe entsteht allein durch die lange Backzeit (Maillard-Reaktion) – ganz ohne Farbstoff." },
    { name: "Roggenbrot", land: "Deutschland", region: EU, kat: "roggen", getreide: "Roggen (mind. 90 %)", trieb: "Sauerteig",
      text: "Aromatisches, leicht säuerliches Brot mit dichter Krume und langer Frischhaltung.",
      fakt: "Ohne Sauerteig wäre Roggen kaum backfähig: Die Säure bremst Enzyme, die sonst die Stärke zu schnell abbauen." },
    { name: "Roggenmischbrot", land: "Deutschland", region: EU, kat: "roggen", getreide: "Roggen (50–90 %) & Weizen", trieb: "Sauerteig & Hefe",
      text: "Der deutsche Alltagsklassiker: kräftiger als Weizenbrot, milder als reines Roggenbrot." },
    { name: "Weizenmischbrot", land: "Deutschland", region: EU, kat: "weizen", getreide: "Weizen (50–90 %) & Roggen", trieb: "Hefe & Sauerteig",
      text: "Heller und milder als Roggenmischbrot, mit lockerer Krume – ein guter Einstieg in die Welt der Mischbrote." },
    { name: "Vollkornbrot", land: "Deutschland", region: EU, kat: "vollkorn", getreide: "Vollkorn (mind. 90 %)", trieb: "Sauerteig oder Hefe",
      text: "Enthält das ganze Korn mit Schale und Keimling – reich an Ballaststoffen und lange sättigend." },
    { name: "Dinkelbrot", land: "Deutschland", region: EU, kat: "weizen", getreide: "Dinkel (mind. 90 %)", trieb: "Hefe oder Sauerteig",
      text: "Nussig-mildes Brot aus Dinkel, einem nahen Verwandten des Weizens. Trocknet schnell aus und wird deshalb oft mit einem Quellstück gebacken." },
    { name: "Schwarzbrot", land: "Norddeutschland", region: EU, kat: "vollkorn", getreide: "Roggenschrot", trieb: "Sauerteig",
      text: "Sammelbegriff für sehr dunkle, kompakte Roggenschrotbrote, oft mit Zuckerrübensirup verfeinert. Hält sich wochenlang." },
    { name: "Kommissbrot", land: "Deutschland", region: EU, kat: "roggen", getreide: "Roggen & Weizen", trieb: "Sauerteig",
      text: "Kastenbrot, das ursprünglich als Soldatenverpflegung („Kommiss“) diente – kompakt, robust und lange haltbar." },
    { name: "Kartoffelbrot", land: "Deutschland", region: EU, kat: "weizen", getreide: "Weizen & Kartoffeln", trieb: "Hefe",
      text: "Gekochte Kartoffeln im Teig machen die Krume besonders saftig und das Brot länger frisch." },
    { name: "Zwiebelbrot", land: "Deutschland", region: EU, kat: "weizen", getreide: "Weizen & Roggen, Röstzwiebeln", trieb: "Hefe",
      text: "Würziges Brot mit gerösteten Zwiebeln – ein Klassiker zur Brotzeit und zum Grillen." },
    { name: "Malzbrot", land: "Deutschland", region: EU, kat: "roggen", getreide: "Roggen & Weizen, Malz", trieb: "Sauerteig & Hefe",
      text: "Durch Malzextrakt dunkel, leicht süßlich und besonders aromatisch." },
    { name: "Sonnenblumenkernbrot", land: "Deutschland", region: EU, kat: "vollkorn", getreide: "Weizen & Roggen, Sonnenblumenkerne", trieb: "Hefe oder Sauerteig",
      text: "Beliebtes Körnerbrot mit nussigem Biss durch geröstete Sonnenblumenkerne." },
    { name: "Mehrkornbrot", alias: "Dreikornbrot, Fünfkornbrot", land: "Deutschland", region: EU, kat: "vollkorn", getreide: "Mind. drei Getreidearten", trieb: "Hefe & Sauerteig",
      text: "Kombiniert mindestens drei verschiedene Getreidearten, zum Beispiel Weizen, Roggen und Hafer." },
    { name: "Einkornbrot", land: "Deutschland", region: EU, kat: "vollkorn", getreide: "Einkorn", trieb: "Sauerteig",
      text: "Gebacken aus Einkorn, einer der ältesten kultivierten Getreidearten. Die Krume ist goldgelb und schmeckt leicht nussig.",
      fakt: "Die gelbe Farbe kommt vom hohen Gehalt an Carotinoiden wie Lutein." },
    { name: "Brötchen", alias: "Semmel, Schrippe, Weck, Rundstück", land: "Deutschland", region: EU, kat: "klein", getreide: "Weizen", trieb: "Hefe",
      text: "Knusprig außen, luftig innen: das Frühstücksgebäck schlechthin – mit unzähligen regionalen Namen." },
    { name: "Röggelchen", land: "Deutschland (Rheinland)", region: EU, kat: "klein", getreide: "Roggen & Weizen", trieb: "Sauerteig",
      text: "Rheinisches Roggen-Doppelbrötchen – untrennbar mit dem „Halven Hahn“ verbunden, einem Röggelchen mit mittelaltem Gouda." },
    { name: "Laugenbrezel", alias: "Breze, Brezn", land: "Süddeutschland", region: EU, kat: "klein", getreide: "Weizen", trieb: "Hefe",
      text: "Vor dem Backen in Natronlauge getaucht – das sorgt für die glänzend braune Kruste und den unverwechselbaren Geschmack.",
      fakt: "Die Brezel ist seit dem Mittelalter das Zunftzeichen der Bäcker." },
    { name: "Schwäbische Seele", land: "Deutschland (Schwaben)", region: EU, kat: "klein", getreide: "Dinkel", trieb: "Hefe",
      text: "Längliches Dinkelgebäck aus sehr weichem Teig, bestreut mit grobem Salz und Kümmel." },
    { name: "Salzstange", land: "Deutschland", region: EU, kat: "klein", getreide: "Weizen", trieb: "Hefe",
      text: "Knusprige Gebäckstange mit grobem Salz und Kümmel – ein beliebter Begleiter zum Bier." },
    { name: "Franzbrötchen", land: "Deutschland (Hamburg)", region: EU, kat: "suess", getreide: "Weizen", trieb: "Hefe",
      text: "Plundergebäck mit Zimt und Zucker, typisch flachgedrückt – Hamburgs Kultgebäck." },
    { name: "Hefezopf", alias: "Zopf, Züpfe", land: "Deutschland & Schweiz", region: EU, kat: "suess", getreide: "Weizen, Milch, Butter", trieb: "Hefe",
      text: "Geflochtenes Brot aus Hefeteig mit Milch und Butter. In Deutschland meist leicht süß, in der Schweiz als „Zopf“ fester Teil des Sonntagsfrühstücks." },
    { name: "Christstollen", alias: "Dresdner Stollen", land: "Deutschland (Sachsen)", region: EU, kat: "suess", getreide: "Weizen, Butter, Rosinen, Zitronat", trieb: "Hefe",
      text: "Schweres, butterreiches Weihnachtsgebäck mit Trockenfrüchten und Puderzucker. Die Form soll an das gewickelte Christkind erinnern.",
      fakt: "„Dresdner Stollen“ ist in der EU als geschützte geografische Angabe eingetragen." },
    { name: "Hutzelbrot", alias: "Früchtebrot, Birnenbrot", land: "Süddeutschland", region: EU, kat: "suess", getreide: "Roggen & Weizen, Dörrobst", trieb: "Sauerteig oder Hefe",
      text: "Dunkles Früchtebrot mit getrockneten Birnen („Hutzeln“), Feigen und Nüssen – ein Adventsklassiker." },
    { name: "Rosinenstuten", land: "Deutschland (Rheinland, Westfalen)", region: EU, kat: "suess", getreide: "Weizen, Rosinen", trieb: "Hefe",
      text: "Weiches, süßes Kastenbrot mit Rosinen – am besten dick mit Butter." },
    { name: "Weckmann", alias: "Stutenkerl, Grittibänz, Klausenmann", land: "Deutschland & Schweiz", region: EU, kat: "suess", getreide: "Weizen", trieb: "Hefe",
      text: "Figur aus Hefeteig, oft mit Tonpfeife, die rund um St. Martin und Nikolaus gebacken wird." },
    { name: "Toastbrot", land: "International", region: EU, kat: "weizen", getreide: "Weizen", trieb: "Hefe",
      text: "In der Kastenform gebacken, mit weicher Krume und dünner Kruste – gemacht für den Toaster." },

    // ---------- Österreich, Schweiz, Südtirol ----------
    { name: "Kaisersemmel", land: "Österreich", region: EU, kat: "klein", getreide: "Weizen", trieb: "Hefe",
      text: "Rundes Brötchen mit fünf sternförmig geschwungenen Segmenten – ein Wiener Klassiker." },
    { name: "Mohnflesserl", land: "Österreich", region: EU, kat: "klein", getreide: "Weizen, Mohn", trieb: "Hefe",
      text: "Geflochtenes Gebäck mit Mohn und Salz, schön knusprig." },
    { name: "Allerheiligenstriezel", land: "Österreich & Bayern", region: EU, kat: "suess", getreide: "Weizen", trieb: "Hefe",
      text: "Süßer Hefezopf, der zu Allerheiligen verschenkt wird – traditionell von Paten an ihre Patenkinder." },
    { name: "Kürbiskernbrot", land: "Österreich (Steiermark)", region: EU, kat: "vollkorn", getreide: "Weizen & Roggen, Kürbiskerne", trieb: "Hefe",
      text: "Grün gesprenkeltes, nussiges Brot mit steirischen Kürbiskernen." },
    { name: "Ruchbrot", land: "Schweiz", region: EU, kat: "weizen", getreide: "Weizen (Ruchmehl)", trieb: "Hefe",
      text: "Schweizer Alltagsbrot aus dunklem Ruchmehl mit kräftiger Kruste." },
    { name: "St. Galler Bürli", land: "Schweiz", region: EU, kat: "klein", getreide: "Weizen & Roggen", trieb: "Hefe",
      text: "Doppel- oder Viererbrötchen mit sehr viel Wasser im Teig, knuspriger Kruste und großporiger Krume – perfekt zur Bratwurst." },
    { name: "Walliser Roggenbrot", land: "Schweiz (Wallis)", region: EU, kat: "roggen", getreide: "Roggen", trieb: "Sauerteig",
      text: "Geschütztes Roggenbrot (AOP) mit rissiger Kruste, das früher auf Vorrat gebacken und wochenlang gelagert wurde." },
    { name: "Vinschgauer", alias: "Vinschger Paarl", land: "Italien (Südtirol)", region: EU, kat: "klein", getreide: "Roggen & Weizen", trieb: "Sauerteig",
      text: "Flaches Roggenbrötchen, gewürzt mit Brotklee, Fenchel und Kümmel." },
    { name: "Schüttelbrot", land: "Italien (Südtirol)", region: EU, kat: "fladen", getreide: "Roggen", trieb: "Sauerteig & Hefe",
      text: "Knusprig-hartes Fladenbrot, dessen Teig durch Schütteln flach verteilt wird. Monatelang haltbar." },

    // ---------- Frankreich ----------
    { name: "Baguette", land: "Frankreich", region: EU, kat: "weizen", getreide: "Weizen", trieb: "Hefe",
      text: "Langes, schlankes Stangenbrot mit knuspriger Kruste und luftiger Krume.",
      fakt: "Seit 2022 gehören Handwerk und Kultur der Baguette zum immateriellen Kulturerbe der UNESCO." },
    { name: "Ficelle", land: "Frankreich", region: EU, kat: "weizen", getreide: "Weizen", trieb: "Hefe",
      text: "Die „Schnur“: eine besonders dünne Baguette mit extra viel Kruste." },
    { name: "Pain de campagne", land: "Frankreich", region: EU, kat: "roggen", getreide: "Weizen & etwas Roggen", trieb: "Sauerteig",
      text: "Französisches Landbrot, rustikal und leicht säuerlich, meist als runder Laib." },
    { name: "Pain au levain", land: "Frankreich", region: EU, kat: "roggen", getreide: "Weizen", trieb: "Sauerteig",
      text: "Reines Sauerteigbrot ohne zugesetzte Hefe, mit offener Krume und tiefem Aroma." },
    { name: "Pain de seigle", land: "Frankreich", region: EU, kat: "roggen", getreide: "Roggen & Weizen", trieb: "Sauerteig",
      text: "Französisches Roggenbrot, das klassisch zu Austern und Meeresfrüchten gereicht wird." },
    { name: "Pain de mie", land: "Frankreich", region: EU, kat: "weizen", getreide: "Weizen, Milch", trieb: "Hefe",
      text: "Kastenweißbrot mit feiner, weicher Krume („mie“) und kaum Kruste." },
    { name: "Walnussbrot", alias: "Pain aux noix", land: "Frankreich", region: EU, kat: "vollkorn", getreide: "Weizen & Roggen, Walnüsse", trieb: "Sauerteig",
      text: "Aromatisches Brot mit großen Walnussstücken – der perfekte Partner für Käse." },
    { name: "Fougasse", land: "Frankreich (Provence)", region: EU, kat: "fladen", getreide: "Weizen, Olivenöl", trieb: "Hefe",
      text: "Provenzalisches Fladenbrot mit blattartigen Einschnitten, oft mit Oliven, Speck oder Kräutern." },
    { name: "Brioche", land: "Frankreich", region: EU, kat: "suess", getreide: "Weizen, Butter, Eier", trieb: "Hefe",
      text: "Luftig-buttriges Hefegebäck, so zart, dass es fast an Kuchen erinnert." },
    { name: "Croissant", land: "Frankreich", region: EU, kat: "klein", getreide: "Weizen, Butter", trieb: "Hefe",
      text: "Blättriges Hörnchen aus touriertem Hefeteig mit vielen Butterschichten.",
      fakt: "In Frankreich zählt es zur „Viennoiserie“ – Gebäck nach Wiener Art, inspiriert vom Kipferl." },
    { name: "Pain d'épices", land: "Frankreich (Burgund, Elsass)", region: EU, kat: "suess", getreide: "Roggen & Weizen, Honig, Gewürze", trieb: "Natron",
      text: "Honig-Gewürzbrot mit Anis, Zimt und Nelken – ein Verwandter des Lebkuchens." },

    // ---------- Italien ----------
    { name: "Ciabatta", land: "Italien", region: EU, kat: "weizen", getreide: "Weizen", trieb: "Hefe mit Vorteig",
      text: "Flaches, längliches Weißbrot aus sehr weichem Teig mit großen, unregelmäßigen Poren.",
      fakt: "Die Ciabatta ist jünger als gedacht: Sie wurde erst 1982 in Venetien entwickelt." },
    { name: "Focaccia", land: "Italien (Ligurien)", region: EU, kat: "fladen", getreide: "Weizen, Olivenöl", trieb: "Hefe",
      text: "Ofenfladenbrot mit viel Olivenöl, grobem Salz und den typischen Fingermulden." },
    { name: "Grissini", land: "Italien (Turin)", region: EU, kat: "klein", getreide: "Weizen", trieb: "Hefe",
      text: "Knusprige, bleistiftdünne Brotstangen aus dem Piemont.",
      fakt: "Der Legende nach wurden sie im 17. Jahrhundert für einen kränklichen jungen Herzog von Savoyen erfunden." },
    { name: "Pane Carasau", alias: "Carta da musica", land: "Italien (Sardinien)", region: EU, kat: "fladen", getreide: "Hartweizen", trieb: "Hefe",
      text: "Hauchdünnes, zweimal gebackenes Fladenbrot – wegen seiner Dünne auch „Notenpapier“ genannt. Hirten nahmen es monatelang mit auf die Weide." },
    { name: "Pane di Altamura", land: "Italien (Apulien)", region: EU, kat: "weizen", getreide: "Hartweizengrieß", trieb: "Sauerteig",
      text: "Goldgelbes Hartweizenbrot mit dicker Kruste – eines der ersten Brote Europas mit geschützter Ursprungsbezeichnung (DOP)." },
    { name: "Pane Toscano", land: "Italien (Toskana)", region: EU, kat: "weizen", getreide: "Weizen", trieb: "Sauerteig",
      text: "Toskanisches Brot ganz ohne Salz – ideal zu würzigem Schinken, Salami und Pecorino.",
      fakt: "Eine Legende erzählt, Pisa habe im Mittelalter Salzlieferungen nach Florenz blockiert." },
    { name: "Piadina", land: "Italien (Romagna)", region: EU, kat: "fladen", getreide: "Weizen, Schmalz oder Olivenöl", trieb: "ungesäuert",
      text: "Dünnes Pfannenfladenbrot, gefüllt mit Schinken, Squacquerone-Käse und Rucola." },
    { name: "Rosetta", alias: "Michetta", land: "Italien", region: EU, kat: "klein", getreide: "Weizen", trieb: "Hefe",
      text: "Rosenförmiges Brötchen, das innen fast hohl ist – ein Verwandter der Kaisersemmel." },
    { name: "Taralli", land: "Italien (Apulien)", region: EU, kat: "klein", getreide: "Weizen, Olivenöl, Weißwein", trieb: "ungesäuert",
      text: "Knusprige Kringel, die vor dem Backen kurz gekocht werden – oft mit Fenchelsamen." },
    { name: "Panettone", land: "Italien (Mailand)", region: EU, kat: "suess", getreide: "Weizen, Butter, Eier, kandierte Früchte", trieb: "Sauerteig (Lievito madre)",
      text: "Hohes, luftiges Weihnachtsbrot, dessen Herstellung mit Sauerteig mehrere Tage dauert." },
    { name: "Pandoro", land: "Italien (Verona)", region: EU, kat: "suess", getreide: "Weizen, Butter, Eier", trieb: "Sauerteig & Hefe",
      text: "Sternförmiges, goldgelbes Weihnachtsgebäck, das mit Puderzucker bestäubt wird." },

    // ---------- Iberische Halbinsel ----------
    { name: "Pan de cristal", land: "Spanien (Katalonien)", region: EU, kat: "weizen", getreide: "Weizen", trieb: "Hefe",
      text: "„Glasbrot“ aus extrem wasserreichem Teig: hauchdünne Kruste, fast hohle Krume." },
    { name: "Pan gallego", land: "Spanien (Galicien)", region: EU, kat: "weizen", getreide: "Weizen", trieb: "Sauerteig",
      text: "Galicisches Landbrot mit dem markanten Teigknoten („moño“) obendrauf." },
    { name: "Pa de pagès", land: "Spanien (Katalonien)", region: EU, kat: "weizen", getreide: "Weizen", trieb: "Sauerteig",
      text: "Katalanisches Bauernbrot – der klassische Untergrund für Pa amb tomàquet." },
    { name: "Coca", land: "Spanien (Katalonien)", region: EU, kat: "fladen", getreide: "Weizen", trieb: "Hefe",
      text: "Blechfladen, herzhaft mit Gemüse belegt oder süß wie die Coca de Sant Joan." },
    { name: "Ensaïmada", land: "Spanien (Mallorca)", region: EU, kat: "suess", getreide: "Weizen, Schweineschmalz", trieb: "Hefe",
      text: "Schneckenförmiges Hefegebäck mit Schmalz („saïm“), dick mit Puderzucker bestreut." },
    { name: "Broa", land: "Portugal", region: EU, kat: "spezial", getreide: "Mais & Roggen", trieb: "Sauerteig",
      text: "Portugiesisches Maisbrot mit dichter, gelber Krume und rissiger Kruste." },
    { name: "Bolo do caco", land: "Portugal (Madeira)", region: EU, kat: "fladen", getreide: "Weizen, Süßkartoffel", trieb: "Hefe",
      text: "Rundes Fladenbrot, das auf einer Basaltplatte („caco“) gebacken und mit Knoblauchbutter serviert wird." },

    // ---------- Britische Inseln ----------
    { name: "Irish Soda Bread", land: "Irland", region: EU, kat: "weizen", getreide: "Weizen, Buttermilch", trieb: "Natron",
      text: "Schnellbrot ohne Hefe: Natron und Buttermilch lassen es aufgehen. Das eingeschnittene Kreuz hilft beim gleichmäßigen Durchbacken." },
    { name: "Barmbrack", land: "Irland", region: EU, kat: "suess", getreide: "Weizen, Trockenobst, Tee", trieb: "Hefe",
      text: "Früchtebrot zu Halloween, in dem traditionell ein Ring versteckt wird – wer ihn findet, soll bald heiraten." },
    { name: "Bara Brith", land: "Wales", region: EU, kat: "suess", getreide: "Weizen, in Tee eingeweichte Früchte", trieb: "Hefe oder Backpulver",
      text: "Das „gesprenkelte Brot“ aus Wales – klassisch zur Teezeit mit gesalzener Butter." },
    { name: "Crumpet", land: "England", region: EU, kat: "klein", getreide: "Weizen", trieb: "Hefe & Natron",
      text: "Pfannenbrötchen mit löchriger Oberseite, das geschmolzene Butter wie ein Schwamm aufsaugt." },
    { name: "English Muffin", land: "England", region: EU, kat: "klein", getreide: "Weizen", trieb: "Hefe",
      text: "Flaches, in der Pfanne gebackenes Hefebrötchen – die Basis für Eggs Benedict." },
    { name: "Cottage Loaf", land: "England", region: EU, kat: "weizen", getreide: "Weizen", trieb: "Hefe",
      text: "Zwei übereinandergesetzte Teiglinge ergeben die typische „Schneemann“-Form." },
    { name: "Hot Cross Bun", land: "England", region: EU, kat: "suess", getreide: "Weizen, Rosinen, Gewürze", trieb: "Hefe",
      text: "Gewürztes Osterbrötchen mit einem Kreuz aus Teig, traditionell am Karfreitag gegessen." },
    { name: "Stottie Cake", land: "England (Nordosten)", region: EU, kat: "fladen", getreide: "Weizen", trieb: "Hefe",
      text: "Flaches, schweres Rundbrot, oft gefüllt mit Schinken und Erbsenpüree." },

    // ---------- Nordeuropa & Baltikum ----------
    { name: "Knäckebröd", land: "Schweden", region: EU, kat: "fladen", getreide: "Roggen", trieb: "Hefe oder ungesäuert",
      text: "Knuspriges, fast wasserfreies Roggenflachbrot – monatelang haltbar.",
      fakt: "Früher wurde es mit einem Loch in der Mitte gebacken, um es auf Stangen unter der Decke zu trocknen." },
    { name: "Tunnbröd", land: "Schweden", region: EU, kat: "fladen", getreide: "Weizen, Gerste, Roggen", trieb: "Hefe oder ungesäuert",
      text: "Nordschwedisches Dünnbrot – gerollt mit Kartoffelpüree und Wurst wird es zur „Tunnbrödsrulle“." },
    { name: "Kanelbulle", land: "Schweden", region: EU, kat: "suess", getreide: "Weizen, Kardamom", trieb: "Hefe",
      text: "Zimtschnecke mit Kardamom im Teig – fester Bestandteil der schwedischen Kaffeepause „Fika“.",
      fakt: "Am 4. Oktober feiert Schweden den Tag der Zimtschnecke." },
    { name: "Vörtbröd", land: "Schweden", region: EU, kat: "suess", getreide: "Roggen & Weizen, Bierwürze", trieb: "Hefe",
      text: "Weihnachtliches Roggenbrot mit Würze („vört“), Sirup und Gewürzen wie Nelke und Pomeranze." },
    { name: "Rugbrød", land: "Dänemark", region: EU, kat: "vollkorn", getreide: "Roggen & Körner", trieb: "Sauerteig",
      text: "Dunkles, saftiges Roggenkörnerbrot – die Grundlage für Smørrebrød." },
    { name: "Ruisleipä", land: "Finnland", region: EU, kat: "roggen", getreide: "Roggenvollkorn", trieb: "Sauerteig",
      text: "Kräftiges finnisches Roggenbrot, oft flach und mit einem Loch in der Mitte.",
      fakt: "2017 wurde es in einer Abstimmung zum Nationalgericht Finnlands gewählt." },
    { name: "Hverabrauð", alias: "Rúgbrauð, Geysirbrot", land: "Island", region: EU, kat: "roggen", getreide: "Roggen", trieb: "Natron",
      text: "Süßliches, dichtes Roggenbrot, das in Töpfen rund 24 Stunden im heißen Boden nahe heißer Quellen gart." },
    { name: "Lefse", land: "Norwegen", region: EU, kat: "fladen", getreide: "Kartoffeln & Weizen", trieb: "ungesäuert",
      text: "Weiches Kartoffelfladenbrot, oft mit Butter, Zucker und Zimt gerollt." },
    { name: "Flatbrød", land: "Norwegen", region: EU, kat: "fladen", getreide: "Gerste, Roggen oder Hafer", trieb: "ungesäuert",
      text: "Hauchdünnes, knuspriges Fladenbrot – traditionell zu Fisch, Fleisch und Suppen." },
    { name: "Rupjmaize", land: "Lettland", region: EU, kat: "roggen", getreide: "Roggen", trieb: "Sauerteig",
      text: "Dunkles Roggenbrot, oft mit Kümmel – daraus wird auch die süße Brotsuppe „Maizes zupa“." },

    // ---------- Ost- & Südosteuropa ----------
    { name: "Borodinsky", land: "Russland", region: EU, kat: "roggen", getreide: "Roggen, Malz", trieb: "Sauerteig",
      text: "Dunkles, süß-säuerliches Roggenbrot mit Koriandersamen und Melasse." },
    { name: "Kalatsch", alias: "Kalach", land: "Ukraine & Russland", region: EU, kat: "weizen", getreide: "Weizen", trieb: "Hefe",
      text: "Weizenbrot in Ringform, geflochten oder mit „Henkel“ – ein Symbol für Wohlstand bei Festen." },
    { name: "Korowai", land: "Ukraine", region: EU, kat: "suess", getreide: "Weizen, Eier", trieb: "Hefe",
      text: "Prächtig verziertes Hochzeitsbrot, das Glück und Fruchtbarkeit symbolisiert." },
    { name: "Paska", land: "Ukraine", region: EU, kat: "suess", getreide: "Weizen, Eier, Butter", trieb: "Hefe",
      text: "Hohes, verziertes Osterbrot, das zur Segnung in die Kirche gebracht wird." },
    { name: "Pampuschky", land: "Ukraine", region: EU, kat: "klein", getreide: "Weizen", trieb: "Hefe",
      text: "Kleine, weiche Brötchen mit Knoblauchöl – die klassische Beilage zum Borschtsch." },
    { name: "Obwarzanek krakowski", land: "Polen (Krakau)", region: EU, kat: "klein", getreide: "Weizen", trieb: "Hefe",
      text: "Gekochter und gebackener Kringel mit Mohn, Sesam oder Salz – ein enger Verwandter des Bagels." },
    { name: "Pogača", land: "Balkan", region: EU, kat: "weizen", getreide: "Weizen", trieb: "Hefe",
      text: "Rundes, weiches Brot, das zu Festen und zur Begrüßung von Gästen gebacken wird." },
    { name: "Somun", alias: "Lepinja", land: "Bosnien und Herzegowina", region: EU, kat: "fladen", getreide: "Weizen", trieb: "Hefe",
      text: "Luftiges Fladenbrot mit Rautenmuster, klassisch gefüllt mit Ćevapi und Zwiebeln." },
    { name: "Česnica", land: "Serbien", region: EU, kat: "weizen", getreide: "Weizen", trieb: "Hefe oder ungesäuert",
      text: "Weihnachtsbrot, in dem eine Münze versteckt wird – wer sie findet, soll im neuen Jahr Glück haben." },
    { name: "Kürtőskalács", alias: "Baumstriezel", land: "Ungarn & Rumänien", region: EU, kat: "suess", getreide: "Weizen", trieb: "Hefe",
      text: "Hefeteig wird um eine Rolle gewickelt, über Glut gedreht und mit Zucker karamellisiert." },
    { name: "Pogácsa", land: "Ungarn", region: EU, kat: "klein", getreide: "Weizen, Butter oder Schmalz", trieb: "Hefe",
      text: "Kleine, mürbe Teigtaler – mit Käse, Grieben oder Kartoffeln." },
    { name: "Cozonac", land: "Rumänien", region: EU, kat: "suess", getreide: "Weizen, Nüsse, Kakao", trieb: "Hefe",
      text: "Süßer Hefezopf mit Nuss- oder Mohnfüllung, gebacken zu Ostern und Weihnachten." },

    // ---------- Griechenland & Türkei ----------
    { name: "Pita", land: "Griechenland", region: EU, kat: "fladen", getreide: "Weizen", trieb: "Hefe",
      text: "Weiches Fladenbrot, in Griechenland meist ohne Tasche – ideal für Gyros und Souvlaki." },
    { name: "Tsoureki", land: "Griechenland", region: EU, kat: "suess", getreide: "Weizen, Mahlab, Mastix", trieb: "Hefe",
      text: "Geflochtenes Osterbrot mit Mahlab und Mastix, oft mit rot gefärbten Eiern verziert." },
    { name: "Koulouri", land: "Griechenland (Thessaloniki)", region: EU, kat: "klein", getreide: "Weizen, Sesam", trieb: "Hefe",
      text: "Sesamring vom Straßenstand – das schnelle griechische Frühstück." },
    { name: "Paximadi", land: "Griechenland (Kreta)", region: EU, kat: "vollkorn", getreide: "Gerste", trieb: "Sauerteig",
      text: "Zweimal gebackener Gerstenzwieback – die Grundlage des kretischen Dakos-Salats." },
    { name: "Lagana", land: "Griechenland", region: EU, kat: "fladen", getreide: "Weizen, Sesam", trieb: "Hefe",
      text: "Flaches Sesambrot, das am „Reinen Montag“ zu Beginn der orthodoxen Fastenzeit gegessen wird." },
    { name: "Simit", land: "Türkei", region: NO, kat: "klein", getreide: "Weizen, Sesam, Traubenmelasse", trieb: "Hefe",
      text: "Knuspriger Sesamring, vor dem Backen in Traubenmelasse getaucht – an jeder Straßenecke Istanbuls zu haben." },
    { name: "Pide", alias: "Ramazan pidesi", land: "Türkei", region: NO, kat: "fladen", getreide: "Weizen, Sesam, Schwarzkümmel", trieb: "Hefe",
      text: "Weiches Fladenbrot mit Rautenmuster, besonders im Ramadan zum Fastenbrechen beliebt." },
    { name: "Bazlama", land: "Türkei", region: NO, kat: "fladen", getreide: "Weizen", trieb: "Hefe",
      text: "Dickes, weiches Pfannenfladenbrot aus Anatolien." },
    { name: "Yufka", land: "Türkei", region: NO, kat: "fladen", getreide: "Weizen", trieb: "ungesäuert",
      text: "Hauchdünne Teigblätter, auf dem gewölbten Blech („sac“) gebacken – gerollt als Dürüm." },

    // ---------- Naher Osten & Kaukasus ----------
    { name: "Lavash", land: "Armenien", region: NO, kat: "fladen", getreide: "Weizen", trieb: "ungesäuert oder Hefe",
      text: "Dünnes, weiches Fladenbrot, das an der Wand des Tonofens „Tonir“ gebacken wird.",
      fakt: "Seit 2014 gehört Lavash zum immateriellen Kulturerbe der UNESCO." },
    { name: "Khachapuri", land: "Georgien", region: NO, kat: "fladen", getreide: "Weizen, Käse", trieb: "Hefe",
      text: "Georgisches Käsebrot. Die adscharische Variante hat Bootsform, mit Ei und Butter in der Mitte." },
    { name: "Shotis Puri", land: "Georgien", region: NO, kat: "weizen", getreide: "Weizen", trieb: "Hefe",
      text: "Kanuförmiges Brot, das an der heißen Innenwand eines runden Tonofens klebt, bis es fertig ist." },
    { name: "Barbari", land: "Iran", region: NO, kat: "fladen", getreide: "Weizen", trieb: "Hefe",
      text: "Langes, dickes Fladenbrot mit Längsrillen und Sesam – das klassische iranische Frühstücksbrot." },
    { name: "Sangak", land: "Iran", region: NO, kat: "fladen", getreide: "Vollkornweizen", trieb: "Sauerteig",
      text: "Auf heißen Kieselsteinen gebackenes Vollkornfladenbrot – der Name bedeutet „kleiner Stein“." },
    { name: "Markook", alias: "Saj-Brot", land: "Levante", region: NO, kat: "fladen", getreide: "Weizen", trieb: "ungesäuert oder Hefe",
      text: "Hauchdünnes Brot, das über einer gewölbten Metallkuppel („saj“) gebacken wird." },
    { name: "Manakish", land: "Libanon", region: NO, kat: "fladen", getreide: "Weizen, Za'atar, Olivenöl", trieb: "Hefe",
      text: "Frühstücksfladen, belegt mit Za'atar und Olivenöl oder mit Käse." },
    { name: "Ka'ak al-Quds", land: "Jerusalem", region: NO, kat: "klein", getreide: "Weizen, Sesam", trieb: "Hefe",
      text: "Länglicher Sesamring, gern mit Za'atar und hartgekochtem Ei gegessen." },
    { name: "Laffa", land: "Irak & Israel", region: NO, kat: "fladen", getreide: "Weizen", trieb: "Hefe",
      text: "Großes, weiches Fladenbrot aus dem Taboon-Ofen – ideal zum Einwickeln von Falafel und Schawarma." },
    { name: "Samoon", land: "Irak", region: NO, kat: "klein", getreide: "Weizen", trieb: "Hefe",
      text: "Rautenförmiges Brot mit knuspriger Kruste und luftigem Inneren." },
    { name: "Challah", alias: "Barches, Berches", land: "Jüdische Küche", region: NO, kat: "suess", getreide: "Weizen, Eier", trieb: "Hefe",
      text: "Geflochtenes Hefebrot für Schabbat und Feiertage; zu Rosch ha-Schana wird es rund gebacken." },
    { name: "Matze", land: "Jüdische Küche", region: NO, kat: "fladen", getreide: "Weizen", trieb: "ungesäuert",
      text: "Ungesäuertes Brot, das zu Pessach gegessen wird.",
      fakt: "Vom Kontakt des Mehls mit Wasser bis zum Backen dürfen höchstens 18 Minuten vergehen." },

    // ---------- Zentral-, Süd- & Ostasien ----------
    { name: "Obi Non", land: "Usbekistan", region: AS, kat: "fladen", getreide: "Weizen", trieb: "Hefe",
      text: "Rundes Brot aus dem Tandyr mit dickem Rand und gestempeltem Muster in der Mitte.",
      fakt: "Brot wird in Zentralasien mit großem Respekt behandelt – man legt es nie mit der Oberseite nach unten." },
    { name: "Baursak", land: "Kasachstan", region: AS, kat: "dampf", getreide: "Weizen", trieb: "Hefe",
      text: "Frittierte Teigbällchen, die bei Festen in großen Mengen auf den Tisch kommen." },
    { name: "Tingmo", land: "Tibet", region: AS, kat: "dampf", getreide: "Weizen", trieb: "Hefe",
      text: "Gedämpftes, spiralförmig gedrehtes Brot – Beilage zu Eintöpfen und Currys." },
    { name: "Naan", land: "Indien & Pakistan", region: AS, kat: "fladen", getreide: "Weizen, Joghurt", trieb: "Hefe",
      text: "Weiches, blasiges Fladenbrot aus dem Tandoor, gern mit Knoblauch oder Butter bestrichen." },
    { name: "Chapati", alias: "Roti", land: "Indien & Ostafrika", region: AS, kat: "fladen", getreide: "Vollkornweizen (Atta)", trieb: "ungesäuert",
      text: "Dünnes Vollkornfladenbrot aus der Pfanne („tawa“) – im indischen Alltag allgegenwärtig." },
    { name: "Paratha", land: "Indien", region: AS, kat: "fladen", getreide: "Vollkornweizen, Ghee", trieb: "ungesäuert",
      text: "Geschichtetes Pfannenbrot mit Ghee, oft gefüllt – etwa mit Kartoffeln als Aloo Paratha." },
    { name: "Puri", land: "Indien", region: AS, kat: "dampf", getreide: "Weizen", trieb: "ungesäuert",
      text: "Kleines Fladenbrot, das sich im heißen Öl wie ein Ballon aufbläht." },
    { name: "Bhatura", land: "Indien (Punjab)", region: AS, kat: "dampf", getreide: "Weizen, Joghurt", trieb: "Hefe",
      text: "Großes frittiertes Brot – als Chole Bhature mit Kichererbsen-Curry serviert." },
    { name: "Kulcha", land: "Indien", region: AS, kat: "fladen", getreide: "Weizen", trieb: "Hefe oder Backpulver",
      text: "Weiches, oft gefülltes Fladenbrot – die Amritsari Kulcha ist legendär." },
    { name: "Rumali Roti", land: "Indien", region: AS, kat: "fladen", getreide: "Weizen", trieb: "ungesäuert",
      text: "Hauchdünn wie ein Taschentuch („rumal“) und über einer gewölbten Pfanne gebacken." },
    { name: "Dosa", land: "Südindien", region: AS, kat: "spezial", getreide: "Reis & Urdbohnen", trieb: "Natürliche Fermentation",
      text: "Knuspriger, fermentierter Pfannkuchen aus Reis und Linsen – von Natur aus glutenfrei." },
    { name: "Appam", land: "Indien (Kerala) & Sri Lanka", region: AS, kat: "spezial", getreide: "Reis, Kokos", trieb: "Natürliche Fermentation",
      text: "Schüsselförmiger Reispfannkuchen mit knusprigem Spitzenrand und weicher Mitte." },
    { name: "Bhakri", land: "Indien", region: AS, kat: "spezial", getreide: "Hirse (Jowar, Bajra)", trieb: "ungesäuert",
      text: "Rustikales Fladenbrot aus Hirse – kräftig, ländlich und glutenfrei." },
    { name: "Mantou", land: "China", region: AS, kat: "dampf", getreide: "Weizen", trieb: "Hefe",
      text: "Schneeweißes, gedämpftes Hefebrötchen – ein Grundnahrungsmittel in Nordchina." },
    { name: "Baozi", land: "China", region: AS, kat: "dampf", getreide: "Weizen", trieb: "Hefe",
      text: "Gedämpfte Teigtaschen mit herzhafter oder süßer Füllung." },
    { name: "Huajuan", land: "China", region: AS, kat: "dampf", getreide: "Weizen", trieb: "Hefe",
      text: "Gedämpfte „Blumenröllchen“, kunstvoll gedreht und oft mit Frühlingszwiebeln gewürzt." },
    { name: "Shaobing", land: "China", region: AS, kat: "fladen", getreide: "Weizen, Sesam", trieb: "Hefe",
      text: "Geschichtetes, gebackenes Sesamfladenbrot, oft aufgeschnitten und gefüllt." },
    { name: "Youtiao", land: "China", region: AS, kat: "dampf", getreide: "Weizen", trieb: "Backpulver & Natron",
      text: "Frittierte Teigstangen, die zum Frühstück in warme Sojamilch getunkt werden." },
    { name: "Cong You Bing", alias: "Frühlingszwiebel-Pfannkuchen", land: "China", region: AS, kat: "fladen", getreide: "Weizen, Frühlingszwiebeln", trieb: "ungesäuert",
      text: "Blättriger Pfannenfladen – außen knusprig, innen weich und würzig." },
    { name: "Bolo Bao", alias: "Ananasbrötchen", land: "Hongkong", region: AS, kat: "suess", getreide: "Weizen, Butter, Zucker", trieb: "Hefe",
      text: "Weiches Brötchen mit knuspriger Zuckerkruste – ganz ohne Ananas, nur das Muster erinnert daran." },
    { name: "Shokupan", alias: "Japanisches Milchbrot", land: "Japan", region: AS, kat: "weizen", getreide: "Weizen, Milch", trieb: "Hefe",
      text: "Extrem weiches, fluffiges Kastenbrot – oft mit der Tangzhong-Methode (Kochstück) gebacken." },
    { name: "Melonpan", land: "Japan", region: AS, kat: "suess", getreide: "Weizen", trieb: "Hefe",
      text: "Süßes Brötchen mit knuspriger Keksteighülle im Melonenmuster – meist ohne Melone." },
    { name: "Anpan", land: "Japan", region: AS, kat: "suess", getreide: "Weizen", trieb: "Hefe (traditionell Sake-Hefe)",
      text: "Weiches Brötchen mit süßer roter Bohnenpaste, 1874 in Tokio erfunden." },
    { name: "Karē-pan", alias: "Currybrot", land: "Japan", region: AS, kat: "dampf", getreide: "Weizen, Panko", trieb: "Hefe",
      text: "Paniertes, frittiertes Brötchen mit japanischer Currysauce im Inneren." },
    { name: "Hotteok", land: "Südkorea", region: AS, kat: "suess", getreide: "Weizen, Klebreismehl", trieb: "Hefe",
      text: "Pfannenbrötchen mit flüssiger Füllung aus braunem Zucker, Zimt und Nüssen – beliebtes Winter-Streetfood." },
    { name: "Bánh mì", land: "Vietnam", region: AS, kat: "weizen", getreide: "Weizen", trieb: "Hefe",
      text: "Vietnamesisches Baguette mit hauchdünner Kruste und sehr leichter Krume – ein Erbe der französischen Kolonialzeit." },
    { name: "Roti Canai", land: "Malaysia", region: AS, kat: "fladen", getreide: "Weizen, Ghee", trieb: "ungesäuert",
      text: "Geschleudertes, vielschichtiges Fladenbrot, serviert mit Curry zum Dippen." },
    { name: "Pandesal", land: "Philippinen", region: AS, kat: "klein", getreide: "Weizen", trieb: "Hefe",
      text: "Weiches, leicht süßes Frühstücksbrötchen mit Semmelbröseln auf der Kruste." },

    // ---------- Afrika ----------
    { name: "Injera", land: "Äthiopien & Eritrea", region: AF, kat: "spezial", getreide: "Teff", trieb: "Natürliche Fermentation",
      text: "Großes, schwammiges Fladenbrot aus Teff mit säuerlichem Geschmack – dient zugleich als Teller und Besteck." },
    { name: "Ambasha", land: "Äthiopien & Eritrea", region: AF, kat: "weizen", getreide: "Weizen, Gewürze", trieb: "Hefe",
      text: "Festtagsbrot mit Koriander und Kardamom und einem kunstvoll eingeritzten Muster." },
    { name: "Aish Baladi", land: "Ägypten", region: AF, kat: "fladen", getreide: "Vollkornweizen", trieb: "Hefe",
      text: "Ägyptisches Vollkornfladenbrot mit Tasche.",
      fakt: "„Aish“ bedeutet im ägyptischen Arabisch auch „Leben“." },
    { name: "Khobz", land: "Marokko", region: AF, kat: "fladen", getreide: "Weizen & Grieß", trieb: "Hefe",
      text: "Rundes, flaches Alltagsbrot, das oft im Gemeinschaftsofen des Viertels gebacken wird." },
    { name: "Batbout", land: "Marokko", region: AF, kat: "fladen", getreide: "Weizen & Grieß", trieb: "Hefe",
      text: "Kleines Pfannenbrot mit Tasche – perfekt zum Füllen." },
    { name: "Msemen", land: "Marokko & Algerien", region: AF, kat: "fladen", getreide: "Weizen & Grieß", trieb: "ungesäuert",
      text: "Quadratisches, geschichtetes Pfannenbrot, zum Frühstück mit Honig und Butter." },
    { name: "Tabouna", land: "Tunesien", region: AF, kat: "fladen", getreide: "Weizen & Grieß", trieb: "Hefe",
      text: "Im gleichnamigen Tonofen gebackenes Fladenbrot mit knuspriger Unterseite." },
    { name: "Taguella", land: "Sahara (Tuareg)", region: AF, kat: "fladen", getreide: "Weizen oder Hirse", trieb: "ungesäuert",
      text: "Brot der Tuareg, direkt im heißen Sand unter der Glut gebacken." },
    { name: "Kisra", land: "Sudan", region: AF, kat: "spezial", getreide: "Sorghum", trieb: "Natürliche Fermentation",
      text: "Dünnes, fermentiertes Sorghum-Fladenbrot – ein Grundnahrungsmittel im Sudan." },
    { name: "Mandazi", land: "Ostafrika", region: AF, kat: "dampf", getreide: "Weizen, Kokosmilch, Kardamom", trieb: "Hefe oder Backpulver",
      text: "Frittiertes, leicht süßes Gebäck – ein Swahili-Klassiker zum Chai." },
    { name: "Agege Bread", land: "Nigeria", region: AF, kat: "weizen", getreide: "Weizen", trieb: "Hefe",
      text: "Weiches, dichtes und leicht süßes Weißbrot aus Lagos – beliebt zu Bohneneintopf." },
    { name: "Puff-Puff", land: "Westafrika", region: AF, kat: "dampf", getreide: "Weizen", trieb: "Hefe",
      text: "Luftige, leicht süße Teigbällchen aus dem Frittierfett – ein beliebter Straßensnack." },
    { name: "Vetkoek", land: "Südafrika", region: AF, kat: "dampf", getreide: "Weizen", trieb: "Hefe",
      text: "„Fettkuchen“: frittierte Teigkugel, gefüllt mit Hackfleisch-Curry oder Konfitüre." },
    { name: "Roosterkoek", land: "Südafrika", region: AF, kat: "klein", getreide: "Weizen", trieb: "Hefe",
      text: "Brötchen, die direkt auf dem Grillrost („braai“) gebacken werden – rauchig und knusprig." },

    // ---------- Amerika ----------
    { name: "San Francisco Sourdough", land: "USA", region: AM, kat: "roggen", getreide: "Weizen", trieb: "Sauerteig",
      text: "Weißes Sauerteigbrot mit ausgeprägter Säure und kräftiger Kruste.",
      fakt: "Ein Milchsäurebakterium trägt den Namen der Stadt: Fructilactobacillus sanfranciscensis." },
    { name: "Cornbread", land: "USA (Südstaaten)", region: AM, kat: "spezial", getreide: "Mais", trieb: "Backpulver",
      text: "Saftiges Maisbrot, oft in der gusseisernen Pfanne gebacken." },
    { name: "Bagel", land: "USA & Polen", region: AM, kat: "klein", getreide: "Weizen", trieb: "Hefe",
      text: "Ringförmiges Brötchen, vor dem Backen kurz gekocht – dicht und angenehm zäh. Kam mit jüdischen Einwanderern aus Osteuropa nach New York." },
    { name: "Buttermilk Biscuits", land: "USA (Südstaaten)", region: AM, kat: "klein", getreide: "Weizen, Butter, Buttermilch", trieb: "Backpulver",
      text: "Luftig-blättrige Brötchen, klassisch mit heller Bratensoße („gravy“)." },
    { name: "Boston Brown Bread", land: "USA (Neuengland)", region: AM, kat: "dampf", getreide: "Roggen, Mais, Vollkornweizen", trieb: "Natron",
      text: "Mit Melasse gesüßtes Brot, das in einer Konservendose gedämpft wird." },
    { name: "Monkey Bread", land: "USA", region: AM, kat: "suess", getreide: "Weizen", trieb: "Hefe",
      text: "Zupfbrot aus Teigkugeln in Zimt-Karamell, das mit den Fingern auseinandergezogen wird." },
    { name: "Frybread", land: "USA (indigene Küche)", region: AM, kat: "dampf", getreide: "Weizen", trieb: "Backpulver",
      text: "Frittiertes Fladenbrot, entstanden im 19. Jahrhundert aus staatlichen Rationen – heute ein vielschichtiges Symbol indigener Küche." },
    { name: "Bannock", land: "Kanada & Schottland", region: AM, kat: "fladen", getreide: "Weizen oder Hafer", trieb: "Backpulver",
      text: "Einfaches Pfannen- oder Lagerfeuerbrot – ursprünglich aus Schottland, heute fest in indigenen Küchen Kanadas verankert." },
    { name: "Tortilla", land: "Mexiko", region: AM, kat: "spezial", getreide: "Mais (nixtamalisiert)", trieb: "ungesäuert",
      text: "Dünner Fladen aus in Kalkwasser gekochtem Mais – seit Jahrtausenden das Fundament der mexikanischen Küche." },
    { name: "Bolillo", land: "Mexiko", region: AM, kat: "klein", getreide: "Weizen", trieb: "Hefe",
      text: "Knuspriges, ovales Brötchen – die Basis für Tortas." },
    { name: "Concha", land: "Mexiko", region: AM, kat: "suess", getreide: "Weizen", trieb: "Hefe",
      text: "Süßes Brötchen mit muschelartig gemusterter Zuckerkruste – der Star unter den „pan dulce“." },
    { name: "Pan de muerto", land: "Mexiko", region: AM, kat: "suess", getreide: "Weizen, Orangenblüte", trieb: "Hefe",
      text: "Wird zum Día de Muertos gebacken; die Teigverzierungen stellen Knochen dar." },
    { name: "Rosca de Reyes", alias: "Roscón de Reyes", land: "Mexiko & Spanien", region: AM, kat: "suess", getreide: "Weizen, kandierte Früchte", trieb: "Hefe",
      text: "Ringförmiges Dreikönigsbrot mit versteckter Figur – wer sie findet, richtet in Mexiko am 2. Februar das nächste Fest aus." },
    { name: "Arepa", land: "Venezuela & Kolumbien", region: AM, kat: "spezial", getreide: "Maismehl", trieb: "ungesäuert",
      text: "Runde, gebratene Maisfladen, aufgeschnitten und üppig gefüllt." },
    { name: "Pan de jamón", land: "Venezuela", region: AM, kat: "suess", getreide: "Weizen", trieb: "Hefe",
      text: "Weihnachtliches Hefebrot, gefüllt mit Schinken, Oliven und Rosinen." },
    { name: "Pão de queijo", land: "Brasilien", region: AM, kat: "spezial", getreide: "Maniokstärke & Käse", trieb: "ungesäuert",
      text: "Kleine, glutenfreie Käsebällchen – außen knusprig, innen elastisch." },
    { name: "Chipa", land: "Paraguay", region: AM, kat: "spezial", getreide: "Maniokstärke & Käse", trieb: "ungesäuert",
      text: "Käsegebäck aus Maniokstärke, oft ringförmig – Paraguays Straßenklassiker." },
    { name: "Marraqueta", alias: "Pan francés", land: "Chile", region: AM, kat: "klein", getreide: "Weizen", trieb: "Hefe",
      text: "Knuspriges Brötchen aus vier aneinanderhängenden Teilen – in Chile zu fast jeder Mahlzeit." },
    { name: "Sopaipilla", land: "Chile & Argentinien", region: AM, kat: "dampf", getreide: "Weizen, Kürbis", trieb: "Backpulver",
      text: "Frittierte Teigfladen mit Kürbis im Teig – in Chile ein Ritual an Regentagen." },
    { name: "Pan cubano", land: "Kuba & USA (Florida)", region: AM, kat: "weizen", getreide: "Weizen, Schmalz", trieb: "Hefe",
      text: "Langes, luftiges Brot mit dünner Kruste – unverzichtbar für das Cubano-Sandwich." },
    { name: "Coco Bread", land: "Jamaika", region: AM, kat: "klein", getreide: "Weizen, Kokosmilch", trieb: "Hefe",
      text: "Gefaltetes Kokosbrötchen, klassisch mit einer Jamaican Patty gefüllt." },
    { name: "Casabe", land: "Karibik & Venezuela", region: AM, kat: "spezial", getreide: "Maniok", trieb: "ungesäuert",
      text: "Großes, knuspriges Fladenbrot aus geriebenem Maniok – schon die Taíno backten es." },

    // ---------- Ozeanien ----------
    { name: "Damper", land: "Australien", region: OZ, kat: "weizen", getreide: "Weizen", trieb: "Backpulver",
      text: "Einfaches Buschbrot, traditionell in der Glut des Lagerfeuers gebacken." },
    { name: "Rēwena Parāoa", land: "Neuseeland (Māori)", region: OZ, kat: "roggen", getreide: "Weizen & Kartoffeln", trieb: "Kartoffel-Sauerteig",
      text: "Māori-Sauerteigbrot mit einem Starter aus fermentierten Kartoffeln („bug“)." },
    { name: "Parāoa Parai", land: "Neuseeland (Māori)", region: OZ, kat: "dampf", getreide: "Weizen", trieb: "Hefe oder Backpulver",
      text: "Frittiertes Brot, gern mit Butter und Golden Syrup gegessen." }
  ];

  const slugify = (s) => s
    .toLowerCase()
    .replace(/ä/g, "ae").replace(/ö/g, "oe").replace(/ü/g, "ue").replace(/ß/g, "ss")
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  BREADS.forEach((b) => { b.id = slugify(b.name); });

  window.GOBROT_DATA = { REGIONS, CATEGORIES, BREADS, slugify };
})();
